export class Book {
  constructor(
    public id?: any,
    public authorList?: any[],
    public editorList?: any[],
    public topicList?: any[],
    public title?: string,
    public comments?: string,
    public weight?: number,
    public subTitle?: string,
    public editor?: any,
    public classification?: any,
    public editionYear?: string,
    public descriptors?: string,
    public pages?: number,
    public size?: string,
    public isbn?: string,
    public topic?: any,
    public salePrice?: number,
    public coin?: string,
    public stockNumber?: number,
    public toShow?: any,
    public file?: any,
    public image?: string,
    public authorText?: string,
    public descriptorList?: any[],
    public visit?: number,
    public createdBy?: string,
    public createdDate?: string,
    public lastModifiedBy?: string,
    public lastModifiedDate?: string,
    public topicsEnglish?: string,
    public topicsSpanish?: string,
    public editors?: string,
    public authors?: string,
    public cities?: string,
    public countriesEnglish?: string,
    public countriesSpanish?: string
  ) {
    this.stockNumber = 0;
  }
}
